import { AccessibilityProfile, TransitStop, TransitLine, RouteCandidate, RouteSegment, RouteScoreBreakdown, RouteExplanation, UserPreferences } from './types';

export const MOCK_TRANSIT_STOPS: Record<string, TransitStop> = {
  stop_gate: {
    id: 'stop_gate',
    name: 'Campus Main Gate & Transit Plaza',
    code: 'CMG-00',
    lat: 42.3582,
    lng: -71.0988,
    type: 'campus_hub',
    zone: 'Campus Main Entrance',
    lightingScore: 9.7,
    cctvCovered: true,
    securityKioskNearby: true,
    blueLightSOS: true,
    stepFree: true,
    hasRamp: true,
    elevatorStatus: 'operational',
    tactilePaving: true,
    audioAnnouncements: true,
    shelterType: 'Heated Glass Enclosed Plaza Canopy',
    crowdLevel: 'moderate',
    description: 'Main campus entry hub with level low-floor bus boarding, ADA curb ramps, and 24/7 Blue Light SOS emergency kiosk.',
    features: ['Low-floor level boarding bays', '24/7 Blue Light SOS kiosk', 'High-intensity LED canopy lighting', 'CCTV monitored safe zone']
  },
  stop_lib: {
    id: 'stop_lib',
    name: 'University Central Library Hub',
    code: 'UCL-01',
    lat: 42.3601,
    lng: -71.0942,
    type: 'campus_hub',
    zone: 'West Campus Safe Corridor',
    lightingScore: 9.8,
    cctvCovered: true,
    securityKioskNearby: true,
    blueLightSOS: true,
    stepFree: true,
    hasRamp: true,
    elevatorStatus: 'operational',
    tactilePaving: true,
    audioAnnouncements: true,
    shelterType: 'Heated Glass Enclosed Hub',
    crowdLevel: 'moderate',
    description: 'Primary accessible interchange on campus. Level boarding, tactile indicators, and automated wheelchair access bridge.',
    features: ['High-intensity LED lights', 'Emergency SOS Blue Light button', 'Wheelchair boarding zone', 'Visual & voice arrivals']
  },
  stop_metro: {
    id: 'stop_metro',
    name: 'Metro Central Station',
    code: 'MCS-12',
    lat: 42.3655,
    lng: -71.1037,
    type: 'metro_station',
    zone: 'Downtown Transit Center',
    lightingScore: 9.5,
    cctvCovered: true,
    securityKioskNearby: true,
    blueLightSOS: true,
    stepFree: false,
    hasRamp: false,
    elevatorStatus: 'broken',
    tactilePaving: true,
    audioAnnouncements: true,
    shelterType: 'Major Underground Transit Hub',
    crowdLevel: 'high',
    description: 'Subway station with 18 concrete stairs at entrance. Primary elevator out of service for repair.',
    features: ['24/7 Transit Police Staffing', 'Braille direction boards', 'High visibility waiting bay']
  },
  stop_hosp: {
    id: 'stop_hosp',
    name: 'City General Hospital & Health Hub',
    code: 'CGH-04',
    lat: 42.3628,
    lng: -71.0765,
    type: 'medical_hub',
    zone: 'Medical District Safe Zone',
    lightingScore: 9.9,
    cctvCovered: true,
    securityKioskNearby: true,
    blueLightSOS: true,
    stepFree: true,
    hasRamp: true,
    elevatorStatus: 'operational',
    tactilePaving: true,
    audioAnnouncements: true,
    shelterType: 'Hospital Main Canopy',
    crowdLevel: 'low',
    description: 'Hospital transit port. Level curb boarding with tactile strips, wheelchair assistance desk, and 24/7 escort.',
    features: ['Wheelchair lending kiosk', 'Security officer post', 'Level curb boarding', 'Heated passenger waiting bay']
  },
  stop_tech: {
    id: 'stop_tech',
    name: 'Innovation Tech Park',
    code: 'ITP-09',
    lat: 42.3702,
    lng: -71.0850,
    type: 'tech_campus',
    zone: 'North Innovation District',
    lightingScore: 9.1,
    cctvCovered: true,
    securityKioskNearby: true,
    blueLightSOS: true,
    stepFree: true,
    hasRamp: true,
    elevatorStatus: 'operational',
    tactilePaving: true,
    audioAnnouncements: true,
    shelterType: 'Smart Solar Glass Shelter',
    crowdLevel: 'moderate',
    description: 'Modern glass platform with tactile paving, automatic low-floor bus ramp, and smart real-time arrival monitors.',
    features: ['Induction charging benches', 'Tactile sidewalk pathways', 'Emergency call phone']
  },
  stop_arts: {
    id: 'stop_arts',
    name: 'East Arts & Cultural District',
    code: 'EAA-07',
    lat: 42.3585,
    lng: -71.0820,
    type: 'street_stop',
    zone: 'East Side Cultural District',
    lightingScore: 6.2,
    cctvCovered: false,
    securityKioskNearby: false,
    blueLightSOS: false,
    stepFree: false,
    hasRamp: false,
    elevatorStatus: 'none',
    tactilePaving: false,
    audioAnnouncements: false,
    shelterType: 'Open Pole Stop',
    crowdLevel: 'moderate',
    description: 'Historic cobblestone area. Steep 8-inch curb step and dimmer heritage lighting. Avoid for wheelchair use.',
    features: ['Cobblestone sidewalk', 'Dim heritage street lamps', 'No weather shelter']
  },
  stop_res: {
    id: 'stop_res',
    name: 'North Student Residences',
    code: 'NSR-03',
    lat: 42.3735,
    lng: -71.0995,
    type: 'residence_stop',
    zone: 'North Campus Living Sector',
    lightingScore: 9.0,
    cctvCovered: true,
    securityKioskNearby: true,
    blueLightSOS: true,
    stepFree: true,
    hasRamp: true,
    elevatorStatus: 'operational',
    tactilePaving: true,
    audioAnnouncements: true,
    shelterType: 'Covered Glass Shed',
    crowdLevel: 'low',
    description: 'Residential campus stop with bright lighting, CCTV camera directly overhead, and emergency SOS pillar.',
    features: ['Residence hall security desk 20m away', 'SOS blue pillar', 'Level boarding platform']
  }
};

export const MOCK_TRANSIT_LINES: Record<string, TransitLine> = {
  line_shuttle: {
    id: 'line_shuttle',
    name: 'SafeCorridor Campus Night Shuttle',
    shortName: 'Shuttle 1A',
    type: 'shuttle',
    color: '#10b981',
    textColor: '#ffffff',
    icon: '🛡️',
    frequencyMin: 8,
    stopsSequence: ['stop_gate', 'stop_lib', 'stop_hosp', 'stop_tech', 'stop_res'],
    crowdLevel: 'low',
    features: {
      lowFloorRamp: true,
      wheelchairBays: 3,
      audioAnnouncements: true,
      visualDisplay: true,
      onboardSafetyGuard: true,
      securityCameras: 4
    }
  },
  line_metro: {
    id: 'line_metro',
    name: 'Metro Blue Line (Downtown Subway)',
    shortName: 'Metro Blue',
    type: 'metro',
    color: '#3b82f6',
    textColor: '#ffffff',
    icon: '🚇',
    frequencyMin: 5,
    stopsSequence: ['stop_gate', 'stop_metro', 'stop_lib', 'stop_arts'],
    crowdLevel: 'high',
    features: {
      lowFloorRamp: true,
      wheelchairBays: 2,
      audioAnnouncements: true,
      visualDisplay: true,
      onboardSafetyGuard: false,
      securityCameras: 8
    }
  },
  line_bus4: {
    id: 'line_bus4',
    name: 'City Rapid Bus 4',
    shortName: 'Bus 4',
    type: 'bus',
    color: '#f59e0b',
    textColor: '#000000',
    icon: '🚌',
    frequencyMin: 12,
    stopsSequence: ['stop_gate', 'stop_lib', 'stop_arts', 'stop_hosp'],
    crowdLevel: 'moderate',
    features: {
      lowFloorRamp: true,
      wheelchairBays: 2,
      audioAnnouncements: true,
      visualDisplay: true,
      onboardSafetyGuard: false,
      securityCameras: 3
    }
  },
  line_green_rail: {
    id: 'line_green_rail',
    name: 'University Light Rail Green',
    shortName: 'Green Rail',
    type: 'light_rail',
    color: '#059669',
    textColor: '#ffffff',
    icon: '🚊',
    frequencyMin: 10,
    stopsSequence: ['stop_gate', 'stop_tech', 'stop_res', 'stop_lib'],
    crowdLevel: 'low',
    features: {
      lowFloorRamp: true,
      wheelchairBays: 4,
      audioAnnouncements: true,
      visualDisplay: true,
      onboardSafetyGuard: true,
      securityCameras: 6
    }
  }
};
